# Generated by Django 5.2 on 2025-10-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcosDoFim', '0003_itens_jogador_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEcosDoFim.itens'),
        ),
    ]
