name: Pipeline de CI/CD Completa

on:
  push:
    branches:
      - main  
      - prod  
  pull_request:
    branches:
      - main  
  workflow_dispatch: 

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      
      - name: Criar ambiente virtual
        run: python -m venv venv 
        
      
      - name: Instalar dependências
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
        
      - name: Rodar testes com pytest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          source venv/bin/activate
          python -m pytest

      
      - name: Limpar arquivos de teste (se os testes passaram)
        run: |
          rm .env
      
      - name: Fazer upload do artefato para o deploy
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    
    needs: build 
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod' # 2. Só roda se for push no 'prod'
    
    permissions:
      id-token: write 
      contents: read 
    steps:
      - name: Baixar artefato do job de build
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E34EDA90DFAD45D7ADF030383BD3D599 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C324C7991E344563BD88A7A4B1E5B949 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ED74961593C748F9A564BB181231D91A }}

      - name: 'Deploy no Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ecos-fim'
          slot-name: 'Production'